# -*- coding: utf-8 -*-
"""deployment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d6uQF4KAHv8fy3uOoMl6Wwu1B2lh9CoJ
"""

# pip install flask-ngrok

# from google.colab import files
# uploaded = files.upload()

#from zipfile import ZipFile

# file_name = '/content/templates.zip'

# with ZipFile(file_name, 'r') as zip:
  # zip.extractall()
 # print('Done')

import flask
from flask import Flask, render_template, request
from flask_ngrok import run_with_ngrok
import os

from keras.models import load_model
from keras.preprocessing import image
import numpy as np

image_folder = os.path.join('static', 'images')
app = Flask(__name__)
run_with_ngrok(app)
app.config["UPLOAD_FOLDER"] = image_folder

model = load_model('myModel.h5')

model.summary()

@app.route('/home', methods=['GET', 'POST'])
def home():
  return render_template('index.html')

@app.route('/predict', methods=['GET', 'POST'])
def predict():
  # predicting images
  imagefile = request.files['imagefile']
  image_path = './static/images/' + imagefile.filename 
  imagefile.save(image_path)

  img = image.load_img(image_path, target_size=(300, 300))
  x = image.img_to_array(img)
  x = np.expand_dims(x, axis=0)

  images = np.vstack([x])
  classes = model.predict(images, batch_size=10)
  new_classes = np.argmax(classes)

  pic = os.path.join(app.config['UPLOAD_FOLDER'], imagefile.filename)
  
  if classes[0] ==0:
    return render_template('index.html', user_image=pic, prediction_text='{} anger'.format(imagefile.filename))
  elif classes[0] ==1:
    return render_template('index.html', user_image=pic, prediction_text='{} disgust'.format(imagefile.filename))
  elif classes[0] ==2:
    return render_template('index.html', user_image=pic, prediction_text='{} fear'.format(imagefile.filename))
  elif classes[0] ==3:
    return render_template('index.html', user_image=pic, prediction_text='{} happiness'.format(imagefile.filename))
  elif classes[0] ==4:
    return render_template('index.html', user_image=pic, prediction_text='{} sadness'.format(imagefile.filename))
  elif classes[0] ==5:
    return render_template('index.html', user_image=pic, prediction_text='{} surprise'.format(imagefile.filename))
  elif classes[0] ==6:
    return render_template('index.html', user_image=pic, prediction_text='{} neutral'.format(imagefile.filename))

# if __name__ == "__main__":
app.run()


